import AVKit
import Foundation
import NitroModules

// ─────────────────────────────────────────────────────────────────────────────
// HybridVideoModule — Top-level Nitro VideoModule for iOS
// Implements HybridVideoModuleSpec generated by Nitrogen.
// Integrates with VideoCacheManager and AVPictureInPictureController.
// ─────────────────────────────────────────────────────────────────────────────

class HybridVideoModule: HybridVideoModuleSpec {

  func isPictureInPictureSupported() throws -> Bool {
    return AVPictureInPictureController.isPictureInPictureSupported()
  }

  func clearVideoCacheAsync() throws -> Promise<Void> {
    let promise = Promise<Void>()
    Task {
      do {
        try await VideoCacheManager.shared.clearAllCache()
        promise.resolve(withResult: ())
      } catch {
        promise.reject(withError: error)
      }
    }
    return promise
  }

  func setVideoCacheSizeAsync(sizeBytes: Double) throws -> Promise<Void> {
    let promise = Promise<Void>()
    do {
      try VideoCacheManager.shared.setMaxCacheSize(newSize: Int(sizeBytes))
      promise.resolve(withResult: ())
    } catch {
      promise.reject(withError: error)
    }
    return promise
  }

  func getCurrentVideoCacheSize() throws -> Double {
    return Double(VideoCacheManager.shared.getCacheDirectorySize())
  }
}
