import AVFoundation
import AVKit
import Foundation
import NitroModules
import UIKit

// ─────────────────────────────────────────────────────────────────────────────
// HybridNitroVideoView — iOS VideoView backed by AVPlayerViewController
// Implements HybridNitroVideoViewSpec generated by Nitrogen.
// Connects to a HybridVideoPlayer via playerId.
// Powered by OrientationAVPlayerViewControllerWrapper.
// ─────────────────────────────────────────────────────────────────────────────

class HybridNitroVideoView: HybridNitroVideoViewSpec, AVPlayerViewControllerDelegate {

  // ─── Native View Controller Wrapper ─────────────────────────────────────────

  private lazy var playerViewControllerWrapper = OrientationAVPlayerViewControllerWrapper(delegate: self)
  var playerViewController: OrientationAVPlayerViewController {
    playerViewControllerWrapper.controller
  }

  // Root UIView exposed for native view embedding / layout
  var view: UIView {
    playerViewControllerWrapper.view
  }

  // ─── Player connection ──────────────────────────────────────────────────────

  weak var connectedPlayer: HybridVideoPlayer?
  private var firstFrameObserver: NSKeyValueObservation?

  override var playerId: Double? {
    didSet { connectPlayer() }
  }

  // ─── Props ──────────────────────────────────────────────────────────────────

  override var nativeControls: Bool = true {
    didSet {
      playerViewController.showsPlaybackControls = nativeControls
    }
  }

  override var contentFit: VideoContentFit = .contain {
    didSet { applyContentFit() }
  }

  override var allowsPictureInPicture: Bool = false {
    didSet {
      VideoManager.shared.setAppropriateAudioSessionOrWarn()
      playerViewController.allowsPictureInPicturePlayback = allowsPictureInPicture
    }
  }

  override var startsPictureInPictureAutomatically: Bool = false {
    didSet {
      #if !os(tvOS)
      playerViewController.canStartPictureInPictureAutomaticallyFromInline = startsPictureInPictureAutomatically
      #endif
    }
  }

  override var requiresLinearPlayback: Bool = false {
    didSet {
      playerViewController.requiresLinearPlayback = requiresLinearPlayback
    }
  }

  override var useExoShutter: Bool = false
  override var controllerAutoShow: Bool = true

  // ─── Callbacks ─────────────────────────────────────────────────────────────

  override var onPictureInPictureStart: (() -> Void)?
  override var onPictureInPictureStop: (() -> Void)?
  override var onFullscreenEnter: (() -> Void)?
  override var onFullscreenExit: (() -> Void)?
  override var onFirstFrameRender: (() -> Void)?

  // ─── Init & Deinit ──────────────────────────────────────────────────────────

  override init() {
    super.init()
    VideoManager.shared.register(videoView: self)
    applyContentFit()
    playerViewController.showsPlaybackControls = nativeControls
  }

  deinit {
    VideoManager.shared.unregister(videoView: self)
    disconnectPlayer()
  }

  // ─── Player connection ──────────────────────────────────────────────────────

  private func connectPlayer() {
    disconnectPlayer()
    guard let pid = playerId.map({ Int($0) }),
          let player = NitroVideoPlayerRegistry.shared.player(forId: pid) else {
      playerViewControllerWrapper.setPlayer(nil)
      return
    }
    connectedPlayer = player
    playerViewControllerWrapper.setPlayer(player)
    addFirstFrameObserver()
  }

  private func disconnectPlayer() {
    removeFirstFrameObserver()
    playerViewControllerWrapper.setPlayer(nil)
    connectedPlayer = nil
  }

  private func addFirstFrameObserver() {
    removeFirstFrameObserver()
    firstFrameObserver = playerViewController.observe(\.isReadyForDisplay) { [weak self] controller, _ in
      if controller.isReadyForDisplay {
        DispatchQueue.main.async {
          self?.onFirstFrameRender?()
        }
      }
    }
  }

  private func removeFirstFrameObserver() {
    firstFrameObserver?.invalidate()
    firstFrameObserver = nil
  }

  // ─── ContentFit ────────────────────────────────────────────────────────────

  private func applyContentFit() {
    playerViewController.videoGravity = contentFit.toVideoGravity()
  }

  // ─── Imperative methods ─────────────────────────────────────────────────────

  override func enterFullscreen() throws -> Promise<Void> {
    DispatchQueue.main.async { [weak self] in
      self?.playerViewController.enterFullscreen(selectorUnsupportedFallback: nil)
    }
    return Promise.resolved(withResult: ())
  }

  override func exitFullscreen() throws -> Promise<Void> {
    DispatchQueue.main.async { [weak self] in
      self?.playerViewController.exitFullscreen()
    }
    return Promise.resolved(withResult: ())
  }

  override func startPictureInPicture() throws -> Promise<Void> {
    let promise = Promise<Void>()
    DispatchQueue.main.async { [weak self] in
      do {
        try self?.playerViewController.startPictureInPicture()
        promise.resolve(withResult: ())
      } catch {
        promise.reject(withError: error)
      }
    }
    return promise
  }

  override func stopPictureInPicture() throws -> Promise<Void> {
    DispatchQueue.main.async { [weak self] in
      self?.playerViewController.stopPictureInPicture()
    }
    return Promise.resolved(withResult: ())
  }

  // ─── AVPlayerViewControllerDelegate ─────────────────────────────────────────

  #if !os(tvOS)
  func playerViewController(
    _ playerViewController: AVPlayerViewController,
    willBeginFullScreenPresentationWithAnimationCoordinator coordinator: UIViewControllerTransitionCoordinator
  ) {
    DispatchQueue.main.async { [weak self] in
      self?.onFullscreenEnter?()
    }
  }

  func playerViewController(
    _ playerViewController: AVPlayerViewController,
    willEndFullScreenPresentationWithAnimationCoordinator coordinator: UIViewControllerTransitionCoordinator
  ) {
    let wasPlaying = connectedPlayer?.playing ?? false
    coordinator.animate(alongsideTransition: nil) { [weak self] context in
      if !context.isCancelled && wasPlaying {
        DispatchQueue.main.async {
          try? self?.connectedPlayer?.play()
        }
      }
      if !context.isCancelled {
        DispatchQueue.main.async {
          self?.onFullscreenExit?()
        }
      }
    }
  }
  #endif

  func playerViewControllerDidStartPictureInPicture(_ playerViewController: AVPlayerViewController) {
    DispatchQueue.main.async { [weak self] in
      self?.onPictureInPictureStart?()
    }
  }

  func playerViewControllerDidStopPictureInPicture(_ playerViewController: AVPlayerViewController) {
    DispatchQueue.main.async { [weak self] in
      self?.onPictureInPictureStop?()
    }
  }

  // ─── Lifecycle ──────────────────────────────────────────────────────────────

  override func onDropView() {
    disconnectPlayer()
  }
}
