import AVFoundation
import AVKit
import Foundation
import MediaPlayer
import NitroModules
import UIKit

// ─────────────────────────────────────────────────────────────────────────────
// HybridVideoPlayer — iOS AVPlayer-backed Nitro HybridObject
// Implements HybridVideoPlayerSpec generated by Nitrogen.
// Fully integrated with VideoSourceLoader, VideoPlayerObserver, VideoPlayerSeeker,
// VideoPlayerAudioTracks, VideoPlayerSubtitles, and NowPlayingManager.
// ─────────────────────────────────────────────────────────────────────────────

class HybridVideoPlayer: HybridVideoPlayerSpec, VideoPlayerObserverDelegate {

  // ─── Static counter & Registry ─────────────────────────────────────────────

  private static var nextPlayerId: Double = 1
  let id: Double

  // ─── Native player & Subsystems ────────────────────────────────────────────

  private(set) var avPlayer: AVPlayer = AVPlayer()
  let videoSourceLoader = VideoSourceLoader()
  lazy var contentKeyManager = ContentKeyManager()
  var observer: VideoPlayerObserver?
  lazy var subtitles: VideoPlayerSubtitles = VideoPlayerSubtitles(owner: self)
  lazy var audioTracks: VideoPlayerAudioTracks = VideoPlayerAudioTracks(owner: self)
  lazy var seeker: VideoPlayerSeeker = VideoPlayerSeeker(player: avPlayer)
  private var dangerousPropertiesStore = DangerousPropertiesStore()
  private var tracksLoadingTask: Task<(), Never>?
  private let didRelease = Mutex(false)

  // ─── Event system ──────────────────────────────────────────────────────────

  private var listenerIdCounter: Int = 0
  private var listeners: [Int: (String, (String) -> Void)] = [:]
  private let listenersLock = NSLock()

  // ─── State ─────────────────────────────────────────────────────────────────

  var status: VideoPlayerStatus = .idle
  private var isPlayingState: Bool = false
  private var currentVideoSource: VideoSource?
  private var currentUri: String = ""
  var bufferOptions = BufferOptions()

  // ─── Init & Deinit ─────────────────────────────────────────────────────────

  override init() {
    let assignedId = HybridVideoPlayer.nextPlayerId
    HybridVideoPlayer.nextPlayerId += 1
    self.id = assignedId
    super.init()

    observer = VideoPlayerObserver(owner: self, videoSourceLoader: videoSourceLoader)
    observer?.registerDelegate(delegate: self)

    // Disable automatic subtitle selection
    let selectionCriteria = AVPlayerMediaSelectionCriteria(preferredLanguages: [], preferredMediaCharacteristics: [.legible])
    avPlayer.setMediaSelectionCriteria(selectionCriteria, forMediaCharacteristic: .legible)

    NitroVideoPlayerRegistry.shared.register(self, forId: Int(assignedId))
    VideoManager.shared.register(videoPlayer: self)
  }

  deinit {
    releasePlayer()
  }

  private func releasePlayer() {
    let alreadyReleased = didRelease.withLock { didRelease in
      defer { didRelease = true }
      return didRelease
    }
    guard !alreadyReleased else { return }

    observer?.notifyPlayerDeinit(player: self)
    observer?.cleanup()
    observer = nil

    NowPlayingManager.shared.unregisterPlayer(self)
    VideoManager.shared.unregister(videoPlayer: self)
    NitroVideoPlayerRegistry.shared.unregister(forId: Int(id))

    videoSourceLoader.close()
    tracksLoadingTask?.cancel()

    runOnMainThread { [weak self] in
      guard let self = self else { return }
      self.avPlayer.pause()
      self.avPlayer.replaceCurrentItem(with: nil)
    }

    listenersLock.lock()
    listeners.removeAll()
    listenersLock.unlock()
  }

  var hasBeenReleased: Bool {
    return didRelease.withLock { $0 }
  }

  // ─── Readonly state ────────────────────────────────────────────────────────

  var playing: Bool {
    return avPlayer.timeControlStatus == .playing
  }

  var duration: Double {
    guard let d = avPlayer.currentItem?.duration else { return 0 }
    let secs = CMTimeGetSeconds(d)
    return secs.isNaN || secs.isInfinite ? 0 : secs
  }

  var isLive: Bool {
    guard let item = avPlayer.currentItem else { return false }
    return item.duration.isIndefinite || item.currentDate() != nil
  }

  var bufferedPosition: Double {
    return getBufferedPosition()
  }

  var isExternalPlaybackActive: Bool {
    return avPlayer.isExternalPlaybackActive
  }

  // ─── Read-write properties ─────────────────────────────────────────────────

  var loop: Bool = false

  var allowsExternalPlayback: Bool {
    get { avPlayer.allowsExternalPlayback }
    set { avPlayer.allowsExternalPlayback = newValue }
  }

  var audioMixingMode: AudioMixingMode = .auto {
    didSet {
      if oldValue != audioMixingMode {
        VideoManager.shared.setAppropriateAudioSessionOrWarn()
      }
    }
  }

  var muted: Bool {
    get { avPlayer.isMuted }
    set {
      let oldMuted = avPlayer.isMuted
      if oldMuted != newValue {
        let payload = MutedChangedEventPayload(muted: newValue, oldMuted: oldMuted)
        safeEmit(event: "mutedChange", payload: payload)
      }
      avPlayer.isMuted = newValue
      VideoManager.shared.setAppropriateAudioSessionOrWarn()
    }
  }

  var currentTime: Double {
    get {
      let time = avPlayer.currentTime().seconds
      return time.isNaN ? 0 : time
    }
    set {
      let clampedTime = max(0, newValue)
      let timeToSeek = CMTimeMakeWithSeconds(clampedTime, preferredTimescale: .max)

      if dangerousPropertiesStore.ownerIsReplacing {
        dangerousPropertiesStore.currentTime = clampedTime
        return
      }

      seeker.seek(to: timeToSeek)
    }
  }

  var volume: Double {
    get { Double(avPlayer.volume) }
    set {
      let oldVolume = Double(avPlayer.volume)
      if oldVolume != newValue {
        let payload = VolumeChangedEventPayload(volume: Float(newValue), oldVolume: Float(oldVolume))
        safeEmit(event: "volumeChange", payload: payload)
      }
      avPlayer.volume = Float(newValue)
    }
  }

  var preservesPitch: Bool = true {
    didSet {
      avPlayer.currentItem?.audioTimePitchAlgorithm = preservesPitch ? .spectral : .varispeed
    }
  }

  var timeUpdateEventInterval: Double = 0 {
    didSet {
      if timeUpdateEventInterval <= 0 {
        observer?.stopTimeUpdates()
        return
      }
      observer?.startOrUpdateTimeUpdates(forInterval: timeUpdateEventInterval)
    }
  }

  var playbackRate: Double = 1.0 {
    didSet {
      if oldValue != playbackRate {
        let payload = PlaybackRateChangedEventPayload(playbackRate: Float(playbackRate), oldPlaybackRate: Float(oldValue))
        safeEmit(event: "playbackRateChange", payload: payload)
      }
      if #available(iOS 16.0, tvOS 16.0, *) {
        avPlayer.defaultRate = Float(playbackRate)
      }
      avPlayer.rate = Float(playbackRate)
    }
  }

  var keepScreenOnWhilePlaying: Bool = true {
    didSet {
      updateIdleTimer()
    }
  }

  var showNowPlayingNotification: Bool = false {
    didSet {
      VideoManager.shared.setAppropriateAudioSessionOrWarn()
      if showNowPlayingNotification {
        NowPlayingManager.shared.registerPlayer(self)
      } else {
        NowPlayingManager.shared.unregisterPlayer(self)
      }
    }
  }

  var staysActiveInBackground: Bool = false {
    didSet {
      if staysActiveInBackground {
        VideoManager.shared.setAppropriateAudioSessionOrWarn()
      }
    }
  }

  // ─── Playback methods ───────────────────────────────────────────────────────

  func load(uri: String, useCaching: Bool, contentType: String) throws {
    guard !uri.isEmpty else {
      clearCurrentItem()
      return
    }
    currentUri = uri

    let url: URL?
    if uri.hasPrefix("/") && !uri.hasPrefix("file://") {
      url = URL(fileURLWithPath: uri)
    } else {
      url = URL(string: uri)
    }

    guard let validUrl = url else {
      let payload = StatusChangedEventPayload(status: .error, oldStatus: status, error: PlaybackError(message: "Invalid URL: \(uri)"))
      safeEmit(event: "statusChange", payload: payload)
      return
    }

    let type = ContentType.from(contentType)
    let source = VideoSource(uri: validUrl, useCaching: useCaching, contentType: type)
    currentVideoSource = source

    Task {
      do {
        try await self.replaceCurrentItem(with: source)
      } catch {
        let payload = StatusChangedEventPayload(status: .error, oldStatus: self.status, error: PlaybackError(message: error.localizedDescription))
        self.safeEmit(event: "statusChange", payload: payload)
      }
    }
  }

  func play() throws {
    avPlayer.play()
    updateIdleTimer()
  }

  func pause() throws {
    avPlayer.pause()
    updateIdleTimer()
  }

  func replaceAsync(uri: String) throws -> Promise<Void> {
    let promise = Promise<Void>()
    guard !uri.isEmpty else {
      clearCurrentItem()
      promise.resolve(withResult: ())
      return promise
    }

    let url: URL?
    if uri.hasPrefix("/") && !uri.hasPrefix("file://") {
      url = URL(fileURLWithPath: uri)
    } else {
      url = URL(string: uri)
    }

    guard let validUrl = url else {
      promise.reject(withError: PlayerItemLoadException("Invalid URL: \(uri)"))
      return promise
    }

    let source = VideoSource(uri: validUrl, useCaching: false, contentType: .auto)
    currentVideoSource = source

    Task {
      do {
        try await self.replaceCurrentItem(with: source)
        promise.resolve(withResult: ())
      } catch {
        promise.reject(withError: error)
      }
    }
    return promise
  }

  func seekBy(seconds: Double) throws {
    let current = avPlayer.currentTime().seconds
    let newTime = CMTimeMakeWithSeconds(max(0, current + seconds), preferredTimescale: .max)
    seeker.seek(to: newTime)
  }

  func replay() throws {
    seeker.seek(to: .zero)
    avPlayer.play()
  }

  func setBufferOptions(options: NitroBufferOptions) throws {
    bufferOptions.preferredForwardBufferDuration = options.preferredForwardBufferDuration
    bufferOptions.waitsToMinimizeStalling = options.waitsToMinimizeStalling
    if options.preferredForwardBufferDuration > 0 {
      avPlayer.currentItem?.preferredForwardBufferDuration = options.preferredForwardBufferDuration
    }
    avPlayer.automaticallyWaitsToMinimizeStalling = options.waitsToMinimizeStalling
  }

  func setSeekTolerance(toleranceBefore: Double, toleranceAfter: Double) throws {
    seeker.seekTolerance = SeekTolerance(toleranceBefore: toleranceBefore, toleranceAfter: toleranceAfter)
  }

  func setScrubbingModeOptions(options: NitroScrubbingModeOptions) throws {
    seeker.scrubbingModeOptions.scrubbingModeEnabled = options.scrubbingModeEnabled
  }

  func setSubtitleTrack(trackId: String) throws {
    if trackId.isEmpty {
      subtitles.selectSubtitleTrack(subtitleTrack: nil)
      return
    }
    let track = subtitles.availableSubtitleTracks.first { $0.id == trackId }
    subtitles.selectSubtitleTrack(subtitleTrack: track)
  }

  func setAudioTrack(trackId: String) throws {
    if trackId.isEmpty {
      audioTracks.selectAudioTrack(audioTrack: nil)
      return
    }
    let track = audioTracks.availableAudioTracks.first { $0.id == trackId }
    audioTracks.selectAudioTrack(audioTrack: track)
  }

  func setMaxResolution(width: Double, height: Double) throws {
    if width > 0 && height > 0 {
      avPlayer.currentItem?.preferredMaximumResolution = CGSize(width: width, height: height)
    } else {
      avPlayer.currentItem?.preferredMaximumResolution = .zero
    }
  }

  func generateThumbnailsAsync(
    times: [Double],
    maxWidth: Double,
    maxHeight: Double
  ) throws -> Promise<[NitroVideoThumbnail]> {
    guard let asset = avPlayer.currentItem?.asset else {
      return Promise.resolved(withResult: [])
    }

    let options = VideoThumbnailOptions(maxWidth: Int(maxWidth), maxHeight: Int(maxHeight))
    let cmTimes = times.map { CMTime(seconds: $0, preferredTimescale: 600) }

    let promise = Promise<[NitroVideoThumbnail]>()
    Task {
      do {
        let thumbnails = try await generateThumbnails(asset: asset, times: cmTimes, options: options)
        let results = thumbnails.map { $0.toNitroThumbnail() }
        promise.resolve(withResult: results)
      } catch {
        promise.reject(withError: error)
      }
    }
    return promise
  }

  // ─── Source replacement ─────────────────────────────────────────────────────

  func replaceCurrentItem(with videoSource: VideoSource?) throws {
    dangerousPropertiesStore.ownerIsReplacing = true
    videoSourceLoader.cancelCurrentTask()
    guard let videoSource = videoSource, let playerItem = VideoPlayerItem(videoSource: videoSource) else {
      clearCurrentItem()
      return
    }

    if let url = videoSource.uri, url.isPHAssetUrl {
      throw PlayerItemLoadException("The provided uri \(url) is a local PHAsset URL. This kind of URL can only be loaded asynchronously. Use `replaceAsync` in order to load this item")
    }

    if let drm = videoSource.drm {
      try drm.type.assertIsSupported()
      contentKeyManager.addContentKeyRequest(videoSource: videoSource, asset: playerItem.urlAsset)
    }

    playerItem.audioTimePitchAlgorithm = preservesPitch ? .spectral : .varispeed
    playerItem.preferredForwardBufferDuration = bufferOptions.preferredForwardBufferDuration

    DispatchQueue.main.async { [weak self] in
      guard let self, !self.hasBeenReleased else { return }
      self.avPlayer.replaceCurrentItem(with: playerItem)
      self.dangerousPropertiesStore.ownerIsReplacing = false
      self.dangerousPropertiesStore.applyProperties(to: self)
    }
  }

  func replaceCurrentItem(with videoSource: VideoSource?) async throws {
    guard let videoSource, videoSource.uri != nil else {
      clearCurrentItem()
      return
    }

    dangerousPropertiesStore.ownerIsReplacing = true
    guard let playerItem = try await videoSourceLoader.load(videoSource: videoSource) else {
      return
    }

    if let drm = videoSource.drm {
      try drm.type.assertIsSupported()
      self.contentKeyManager.addContentKeyRequest(videoSource: videoSource, asset: playerItem.urlAsset)
    }

    playerItem.audioTimePitchAlgorithm = self.preservesPitch ? .spectral : .varispeed
    playerItem.preferredForwardBufferDuration = self.bufferOptions.preferredForwardBufferDuration

    DispatchQueue.main.async { [weak self] in
      guard let self, !self.hasBeenReleased else { return }
      self.avPlayer.replaceCurrentItem(with: playerItem)
      self.dangerousPropertiesStore.ownerIsReplacing = false
      self.dangerousPropertiesStore.applyProperties(to: self)
    }
  }

  func reloadCurrentSource() {
    guard let videoSource = (avPlayer.currentItem as? VideoPlayerItem)?.videoSource else {
      return
    }

    let resumeTime = currentTime
    let wasPlaying = playing

    Task { [weak self] in
      guard let self else { return }
      if resumeTime > 0 {
        self.dangerousPropertiesStore.currentTime = resumeTime
      }
      do {
        try await self.replaceCurrentItem(with: videoSource)
      } catch {
        print("[nitro-video] Failed to reload video source: \(error.localizedDescription)")
        return
      }

      if wasPlaying {
        await MainActor.run {
          self.avPlayer.play()
        }
      }
    }
  }

  func reloadIfFailed() {
    if avPlayer.status == .failed || avPlayer.currentItem?.status == .failed {
      reloadCurrentSource()
    }
  }

  private func clearCurrentItem() {
    videoSourceLoader.cancelCurrentTask()

    DispatchQueue.main.async { [weak self] in
      guard let self else { return }
      self.avPlayer.replaceCurrentItem(with: nil)
      self.dangerousPropertiesStore.reset()
      self.dangerousPropertiesStore.ownerIsReplacing = false
    }
  }

  private func getBufferedPosition() -> Double {
    guard let currentItem = avPlayer.currentItem else { return -1 }
    let currentTime = avPlayer.currentTime().seconds

    for timeRange in currentItem.loadedTimeRanges {
      let start = CMTimeGetSeconds(timeRange.timeRangeValue.start)
      let end = CMTimeGetSeconds(timeRange.timeRangeValue.end)
      if start <= currentTime && end >= currentTime {
        return end
      }
    }
    return 0
  }

  private func updateIdleTimer() {
    DispatchQueue.main.async { [weak self] in
      guard let self else { return }
      UIApplication.shared.isIdleTimerDisabled = self.keepScreenOnWhilePlaying && self.playing
    }
  }

  // ─── VideoPlayerObserverDelegate ───────────────────────────────────────────

  func onStatusChanged(player: AVPlayer, oldStatus: VideoPlayerStatus?, newStatus: VideoPlayerStatus, error: Error?) {
    self.status = newStatus
    let errorRecord = error != nil ? PlaybackError(message: error?.localizedDescription) : nil
    let payload = StatusChangedEventPayload(status: newStatus, oldStatus: oldStatus, error: errorRecord)
    safeEmit(event: "statusChange", payload: payload)
  }

  func onIsPlayingChanged(player: AVPlayer, oldIsPlaying: Bool?, newIsPlaying: Bool) {
    self.isPlayingState = newIsPlaying
    let payload = IsPlayingEventPayload(isPlaying: newIsPlaying, oldIsPlaying: oldIsPlaying)
    safeEmit(event: "playingChange", payload: payload)
    VideoManager.shared.setAppropriateAudioSessionOrWarn()
    updateIdleTimer()
  }

  func onRateChanged(player: AVPlayer, oldRate: Float?, newRate: Float) {
    if #available(iOS 16.0, tvOS 16.0, *) {
      if player.defaultRate != Float(playbackRate) {
        playbackRate = Double(player.defaultRate)
      }
    } else if newRate != 0 && newRate != Float(playbackRate) {
      avPlayer.rate = Float(playbackRate)
    }
    let payload = PlaybackRateChangedEventPayload(playbackRate: newRate, oldPlaybackRate: oldRate ?? 1.0)
    safeEmit(event: "playbackRateChange", payload: payload)
  }

  func onVolumeChanged(player: AVPlayer, oldVolume: Float?, newVolume: Float) {
    let payload = VolumeChangedEventPayload(volume: newVolume, oldVolume: oldVolume ?? 1.0)
    safeEmit(event: "volumeChange", payload: payload)
  }

  func onIsMutedChanged(player: AVPlayer, oldIsMuted: Bool?, newIsMuted: Bool) {
    let payload = MutedChangedEventPayload(muted: newIsMuted, oldMuted: oldIsMuted ?? false)
    safeEmit(event: "mutedChange", payload: payload)
    VideoManager.shared.setAppropriateAudioSessionOrWarn()
  }

  func onPlayedToEnd(player: AVPlayer) {
    safeEmit(event: "playToEnd", payload: PlayToEndEventPayload())
    if loop {
      seeker.seek(to: .zero)
      avPlayer.play()
    }
  }

  func onItemChanged(player: AVPlayer, oldVideoPlayerItem: VideoPlayerItem?, newVideoPlayerItem: VideoPlayerItem?) {
    let payload = SourceChangedEventPayload(
      source: newVideoPlayerItem?.videoSource,
      oldSource: oldVideoPlayerItem?.videoSource
    )
    safeEmit(event: "sourceChange", payload: payload)
    newVideoPlayerItem?.preferredForwardBufferDuration = bufferOptions.preferredForwardBufferDuration
  }

  func onTimeUpdate(player: AVPlayer, timeUpdate: TimeUpdate) {
    safeEmit(event: "timeUpdate", payload: timeUpdate)
  }

  func onLoadedPlayerItem(player: AVPlayer, playerItem: AVPlayerItem?) {
    guard !hasBeenReleased else { return }
    tracksLoadingTask?.cancel()
    tracksLoadingTask = Task { [weak self] in
      guard let self else { return }
      let audioPayload = await self.audioTracks.onNewPlayerItemLoaded(playerItem: playerItem)
      let subtitlesPayload = await self.subtitles.onNewPlayerItemLoaded(playerItem: playerItem)
      let videoPlayerItem = playerItem as? VideoPlayerItem
      let videoTracks = await videoPlayerItem?.videoTracks ?? []

      guard !Task.isCancelled else { return }

      let dur = playerItem?.duration.seconds
      let validDuration = (dur != nil && !dur!.isNaN && dur! > 0) ? dur : nil

      let videoSourceLoadedPayload = VideoSourceLoadedEventPayload(
        videoSource: videoPlayerItem?.videoSource,
        duration: validDuration,
        availableVideoTracks: videoTracks,
        availableSubtitleTracks: self.subtitles.availableSubtitleTracks,
        availableAudioTracks: self.audioTracks.availableAudioTracks
      )

      self.safeEmit(event: "sourceLoad", payload: videoSourceLoadedPayload)
      self.safeEmit(event: "availableSubtitleTracksChange", payload: subtitlesPayload)
      self.safeEmit(event: "availableAudioTracksChange", payload: audioPayload)
    }
  }

  func onSubtitleSelectionChanged(player: AVPlayer, playerItem: AVPlayerItem?, subtitleTrack: SubtitleTrack?) {
    let oldTrack = subtitles.currentSubtitleTrack
    subtitles.onNewSubtitleTrackSelected(subtitleTrack: subtitleTrack)
    let payload = SubtitleTrackChangedEventPayload(subtitleTrack: subtitles.currentSubtitleTrack, oldSubtitleTrack: oldTrack)
    safeEmit(event: "subtitleTrackChange", payload: payload)
  }

  func onAudioTrackSelectionChanged(player: AVPlayer, playerItem: AVPlayerItem?, audioTrack: AudioTrack?) {
    let oldTrack = audioTracks.currentAudioTrack
    audioTracks.onNewAudioTrackSelected(audioTrack: audioTrack)
    let payload = AudioTrackChangedEventPayload(audioTrack: audioTracks.currentAudioTrack, oldAudioTrack: oldTrack)
    safeEmit(event: "audioTrackChange", payload: payload)
  }

  func onVideoTrackChanged(player: AVPlayer, oldVideoTrack: VideoTrack?, newVideoTrack: VideoTrack?) {
    let payload = VideoTrackChangedEventPayload(videoTrack: newVideoTrack, oldVideoTrack: oldVideoTrack)
    safeEmit(event: "videoTrackChange", payload: payload)
  }

  func onIsExternalPlaybackActiveChanged(player: AVPlayer, oldIsExternalPlaybackActive: Bool?, newIsExternalPlaybackActive: Bool) {
    let payload = IsExternalPlaybackActiveEventPayload(
      isExternalPlaybackActive: newIsExternalPlaybackActive,
      oldIsExternalPlaybackActive: oldIsExternalPlaybackActive
    )
    safeEmit(event: "isExternalPlaybackActiveChange", payload: payload)
  }

  func onPlayerDeinit(player: HybridVideoPlayer) {}

  // ─── Event emission & subscription ──────────────────────────────────────────

  func addListener(event: String, callback: @escaping (String) -> Void) throws -> Double {
    listenersLock.lock()
    defer { listenersLock.unlock() }
    listenerIdCounter += 1
    listeners[listenerIdCounter] = (event, callback)
    return Double(listenerIdCounter)
  }

  func removeListener(listenerId: Double) throws {
    listenersLock.lock()
    defer { listenersLock.unlock() }
    listeners.removeValue(forKey: Int(listenerId))
  }

  func safeEmit<T: Codable>(event: String, payload: T? = nil) {
    let jsonString: String
    if let payload = payload {
      jsonString = payload.toJSONString()
    } else {
      jsonString = "{}"
    }

    DispatchQueue.main.async { [weak self] in
      guard let self else { return }
      self.listenersLock.lock()
      let matched = self.listeners.values.filter { $0.0 == event }
      self.listenersLock.unlock()

      for listener in matched {
        listener.1(jsonString)
      }
    }
  }
}
